name: adidas-monorepo

services:
  - name: frontend
    type: web
    env: docker
    repo: https://github.com/<your-org-or-username>/<repo-name>
    dockerfilePath: ./apps/web/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://api-gateway.onrender.com
    plan: free

  - name: api-gateway
    type: web
    env: docker
    repo: https://github.com/<your-org-or-username>/<repo-name>
    dockerfilePath: ./apps/gateway/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: USERS_SERVICE_URL
        value: https://users-service.onrender.com
      - key: PRODUCTS_SERVICE_URL
        value: https://products-service.onrender.com
      - key: ORDERS_SERVICE_URL
        value: https://orders-service.onrender.com
      - key: STRIPE_SERVICE_URL
        value: https://stripe-service.onrender.com
    plan: free

  - name: users-service
    type: web
    env: docker
    repo: https://github.com/<your-org-or-username>/<repo-name>
    dockerfilePath: ./services/users/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${users-db.DATABASE_URL}
    plan: free

  - name: products-service
    type: web
    env: docker
    repo: https://github.com/<your-org-or-username>/<repo-name>
    dockerfilePath: ./services/products/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${products-db.DATABASE_URL}
    plan: free

  - name: orders-service
    type: web
    env: docker
    repo: https://github.com/<your-org-or-username>/<repo-name>
    dockerfilePath: ./services/orders/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${orders-db.DATABASE_URL}
    plan: free

  - name: stripe-service
    type: web
    env: docker
    repo: https://github.com/<your-org-or-username>/<repo-name>
    dockerfilePath: ./services/stripe/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false
    plan: free

databases:
  - name: users-db
    plan: free
    postgresMajorVersion: 15

  - name: products-db
    plan: free
    postgresMajorVersion: 15

  - name: orders-db
    plan: free
    postgresMajorVersion: 15
