services:
  web:
    build: .
    ports:
      - "7217:80"
    volumes:
      - aspnet-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80

volumes:
  aspnet-keys: {}
