# Elasticsearch Configuration
cluster.name: "adidas-search"
node.name: "adidas-node-1"

# Network
network.host: 0.0.0.0
http.port: 9200

# Discovery
discovery.type: single-node

# Security (disabled for development)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false

# Memory
bootstrap.memory_lock: false

# Paths
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Performance
indices.query.bool.max_clause_count: 10000
